src/DependencyInjection/Models/ErrorViewModel.cs
namespace DependencyInjection.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/DependencyInjection/Controllers/HomeController.cs
using DependencyInjection.Models;
using DependencyInjection.Options;
using DependencyInjection.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System.Diagnostics;

namespace DependencyInjection.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly GuidWrapperService _guidWrapperService;
        private readonly ISingletonGuidService _singletonGuidService;
        private readonly IScopedGuidService _scopedGuidService;
        private readonly ITransientGuidService _transientGuidService;
        private readonly IOptionsSnapshot<DatabaseOptions> _databaseOptionsSnapshot;

        public HomeController(
            ILogger<HomeController> logger,
            GuidWrapperService guidWrapperService,
            ISingletonGuidService singletonGuidService,
            IScopedGuidService scopedGuidService,
            ITransientGuidService transientGuidService,
            IOptionsSnapshot<DatabaseOptions> databaseOptionsSnapshot)
        {
            _logger = logger;

            _guidWrapperService = guidWrapperService;
            _singletonGuidService = singletonGuidService;
            _scopedGuidService = scopedGuidService;
            _transientGuidService = transientGuidService;
            _databaseOptionsSnapshot = databaseOptionsSnapshot;
        }

        public IActionResult Index()
        {
            ViewBag.Singleton = _singletonGuidService.GetGuid();
            ViewBag.Scoped = _scopedGuidService.GetGuid();
            ViewBag.Transient = _transientGuidService.GetGuid();

            ViewBag.WSingleton = _guidWrapperService.GetSingletonGuid();
            ViewBag.WScoped = _guidWrapperService.GetScopedGuid();
            ViewBag.WTransient = _guidWrapperService.GetTransientGuid();

            return View();
        }

        public IActionResult Options()
        {
            var databaseOptions = _databaseOptionsSnapshot.Value;

            ViewBag.Username = databaseOptions.Username;
            ViewBag.Password = databaseOptions.Password;
            ViewBag.Hostname = databaseOptions.Hostname;
            ViewBag.Port = databaseOptions.Port;

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/DependencyInjection/Controllers/OptionsController.cs
using DependencyInjection.Options;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace DependencyInjection.Controllers
{
    public class OptionsController : Controller
    {

        private readonly IOptions<DatabaseOptions> _databaseOptions;
        private readonly IOptions<ExternalOptions> _externalOptions;

        public OptionsController(
            IOptions<DatabaseOptions> databaseOptions,
            IOptions<ExternalOptions> externalOptions
            )
        {
            _databaseOptions = databaseOptions;
            _externalOptions = externalOptions;
        }

        public IActionResult Index()
        {
            var databaseOptions = _databaseOptions.Value;

            ViewBag.Username = databaseOptions.Username;
            ViewBag.Password = databaseOptions.Password;
            ViewBag.Hostname = databaseOptions.Hostname;
            ViewBag.Port = databaseOptions.Port;

            var externalOptions = _externalOptions.Value;

            ViewBag.ConnectionString = externalOptions.ConnectionString;

            return View();
        }
    }
}

src/DependencyInjection/Controllers/UpdatedOptionsController.cs
using DependencyInjection.Options;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace DependencyInjection.Controllers
{
    public class UpdatedOptionsController : Controller
    {

        private readonly IOptionsSnapshot<DatabaseOptions> _databaseOptionsSnapshot;
        private readonly IOptionsSnapshot<ExternalOptions> _externalOptionsSnapshot;

        public UpdatedOptionsController(
            IOptionsSnapshot<DatabaseOptions> databaseOptionsSnapshot,
            IOptionsSnapshot<ExternalOptions> externalOptionsSnapshot)
        {
            _databaseOptionsSnapshot = databaseOptionsSnapshot;
            _externalOptionsSnapshot = externalOptionsSnapshot;
        }

        public IActionResult Index()
        {
            var databaseOptions = _databaseOptionsSnapshot.Value;

            ViewBag.Username = databaseOptions.Username;
            ViewBag.Password = databaseOptions.Password;
            ViewBag.Hostname = databaseOptions.Hostname;
            ViewBag.Port = databaseOptions.Port;

            var externalOptions = _externalOptionsSnapshot.Value;

            ViewBag.ConnectionString = externalOptions.ConnectionString;

            return View();
        }
    }
}

src/DependencyInjection/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<p>
    <h1>Controller</h1>
    <ul>
        <li>Singleton: @ViewBag.Singleton</li>
        <li>Scoped: @ViewBag.Scoped</li>
        <li>Transient: @ViewBag.Transient</li>
    </ul>
</p>

<p>
    <h1>Service</h1>
    <ul>
        <li>Singleton: @ViewBag.WSingleton</li>
        <li>Scoped: @ViewBag.WScoped</li>
        <li>Transient: @ViewBag.WTransient</li>
    </ul>
</p>

src/DependencyInjection/Views/Options/Index.cshtml
@{
    ViewData["Title"] = "Options";
}

<p>
    <h1>Database:</h1>
    <ul>
        <li>Username: @ViewBag.Username</li>
        <li>Password: @ViewBag.Password</li>
        <li>Hostname: @ViewBag.Hostname</li>
        <li>Port: @ViewBag.Port</li>
    </ul>
</p>
<p>
    <h1>External:</h1>
    <ul>
        <li>Connectionstring: @ViewBag.ConnectionString</li>
    </ul>
</p>
<p>
    Read more here: <i>https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0</i>
</p>

src/DependencyInjection/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DependencyInjection</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetCore.DependencyInjection.BuiltIn</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Options" asp-action="Index">Options</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UpdatedOptions" asp-action="Index">Updated Options</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AspNetCore.DependencyInjection.BuiltIn - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/DependencyInjection/Views/UpdatedOptions/Index.cshtml
@{
    ViewData["Title"] = "Updated Options";
}

<p>
    <h1>Database:</h1>
    <ul>
        <li>Username: @ViewBag.Username</li>
        <li>Password: @ViewBag.Password</li>
        <li>Hostname: @ViewBag.Hostname</li>
        <li>Port: @ViewBag.Port</li>
    </ul>
</p>
<p>
    <h1>External:</h1>
    <ul>
        <li>Connectionstring: @ViewBag.ConnectionString</li>
    </ul>
</p>
<p>
    Read more here: <i>https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0</i>
</p>